/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    CommitReveal: {
      address: "0x0e815EDbdFbA4E9180892b925698B2c03783Fd18",
      abi: [
        {
          type: "function",
          name: "blocksUntilExpiry",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "blocksLeft",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "computeHash",
          inputs: [
            {
              name: "secret",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "salt",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "commit",
          inputs: [
            {
              name: "dataHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "commitments",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "dataHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "commitBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "revealed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCommitment",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "dataHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "commitBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "revealed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reveal",
          inputs: [
            {
              name: "secret",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "salt",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "randomSeed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Committed",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "dataHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "commitBlock",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Revealed",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "secret",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "salt",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "randomSeed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 42156155,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
